### ISSUE TITLE
Enharmonic notes not supported

### ISSUE THREAD

**Issue by stufro** [cheerfulstoic/music#8]
Thanks for the gem, it has helped me greatly with my own project!

If you try to initialise a `Note` with an enharmonic note such as `E#`, the following exception is raised:

```
irb(main):001:0> note = Music::Note.new("E#", 5)
/Users/stuart/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/music-0.7.0/lib/music/note.rb:278:in `note_distance': undefined method `-' for nil:NilClass (NoMethodError)

        (index2 - index1) + ((octave2.to_i - octave1.to_i) * NOTES.size)
                ^
```

I will try to have a look, raise a PR and report back.

**Comment by cheerfulstoic** [comment]
🎉  I haven't looked at this project for a while, but by all means if you make a PR I'll have a look 👍
